### ISSUE TITLE
Upgrade Base Image of nginxinc/docker-nginx-unprivileged from stable-bullseye to stable-bookworm

### ISSUE THREAD

**Issue by michealch** [nginxinc/docker-nginx-unprivileged#183]
### Is your feature request related to a problem? Please describe
Debian 12 has less CVS than Debian 11.
Trivy Scan results:
<img width="571" alt="Screenshot 2024-02-02 at 11 31 56" src="https://github.com/nginxinc/docker-nginx-unprivileged/assets/23565623/723cf765-5b1a-49cd-a68b-620d6ac1b8d6">
<img width="538" alt="Screenshot 2024-02-02 at 11 32 05" src="https://github.com/nginxinc/docker-nginx-unprivileged/assets/23565623/a377a0f8-0956-4fc1-b037-26f7b2d98668">

### Describe the solution you'd like

The solution would be to update the base image from Debian stable-bullseye to Debian stable-bookworm.

### Describe alternatives you've considered

----

### Additional context

--

**Comment by 24367dfa** [comment]
the debian project currently designates bullseye as `oldstable` and bookkworm as `stable`.

this should be reflected in the tags for the nginx-unprivileged container.

**Comment by michealch** [comment]
It would be great if the image tag naming convention could align with the server versioning format, specifically using the structure: MAJOR.MINOR.PATCH-$(os-version).

**Comment by michealch** [comment]
> this is already available as `nginx-unprivileged:mainline/nginx-unprivileged:bookworm`

Correct me please, if I am wrong. As far as I know, the mainline version is 1.25.3, which, according to the official NGINX website, is not stable. According to the NGINX Inc. website, 1.24.x is stable and received its latest update on April 11, 2023.

**Comment by alessfg** [comment]
There are three things to comment on here:
1. This is an unprivileged port of the Docker NGINX images/repo. The naming convention here is not going to change unless the Docker NGINX images change their naming convention too. If you want to propose any changes (such as adding additional tags -- we are not going to remove the tag system already in use), I'd suggest you bring it up here https://github.com/nginxinc/docker-nginx.
2. Following up from 1., the Docker NGINX image only bumps base os images when there's a new NGINX release. There has not been a stable NGINX release since Debian bookworm was released, and thus the stable image has not been bumped to it yet. See this issue for some of the reasoning from the maintainer of the core project https://github.com/nginxinc/docker-nginx/issues/847.
3. While the `stable` branch is obviously more `stable`, that does not mean that the `mainline` branch is not stable. All new development and features is made on the `mainline` branch, and then once a year those changes get back-ported to the `stable` branch. In fact, NGINX Plus, NGINX's enterprise offering, is built on the latest `mainline` releases, which just goes to show how stable it is.

**Comment by alessfg** [comment]
I've gone ahead and updated the README to hopefully make some of the points raised here a bit more clear https://github.com/nginxinc/docker-nginx-unprivileged/commit/3ae099e9b004f93b409b65a89e08288b0c9ff576
