### ISSUE TITLE
Write permission issue when running as random user

### ISSUE THREAD

**Issue by mteodori** [nginxinc/docker-nginx-unprivileged#54]
If I try and run with a different user and group I get a write permission error on included files where replacements need to be performed like `/etc/nginx/conf.d/default.conf`:

```bash
➜ docker run --rm -it --publish 8080:8080 --user 1000:1000 nginxinc/nginx-unprivileged:1.19.3-alpine
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by alessfg** [comment]
I don't know that that's something that can be easily addressed since by virtue of how the whole system is configured only the NGINX user has write permissions where relevant. You might have to mount your config file as a volume if you want to run the image as a different user. (FWIW, the only change made by that script is to enable `ipv6` if it's supported in your environment.)

**Comment by mteodori** [comment]
thanks @alessfg makes sense for me to use a volume and do not leverage the existing environment variable support in the base image, we can close this
