### ISSUE TITLE
critical security vulnerabilities with version 1.21 alpine 1.21-alpine

### ISSUE THREAD

**Issue by abdennour** [nginxinc/docker-nginx-unprivileged#77]
# Overview
curl package has CRITICAL issue in image 1.21

# Steps to reproduce

```sh
alias scan='docker run -it --rm quay.io/ighup/trivy-offline image --skip-update'
scan nginxinc/nginx-unprivileged:1.21-alpine
```

# Actual results:

Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 2, CRITICAL: 2)

![image](https://user-images.githubusercontent.com/1788384/140040468-9a7af430-7bfe-49b3-93d3-a23bff6b9cdc.png)

# Excepted Results:

High: 0 , Critical: 0 , MEDIUM: <Low_number>, LOW:  <whatever>

**Comment by alessfg** [comment]
Hey @abdennour! Next time you create a security issue can you check for past issues and also whether the package at hand is actually used in the image? I'll link a past reply that goes over this issue specifically:
https://github.com/nginxinc/docker-nginx-unprivileged/issues/73#issuecomment-893423856

**Comment by abdennour** [comment]
still i didn't get the reason of closing this issue without action, @alessfg

**Comment by alessfg** [comment]
Well fundamentally because there is no action that needs to be taken immediately. Those vulnerabilities do not affect these images unless you plan to use `curl` later down the line. And if you do so, you can very easily extend this image to update `curl`. There's a new NGINX mainline release (`1.21.4`) so new images will be built and pushed next week.
