### ISSUE TITLE
Still has 1 high vulnerability issue in nginxinc/nginx-unprivileged@sha256:54b2d0d8ab8891225a824a1e3e1980ee187f17518517a778e7bacb476731a62b

### ISSUE THREAD

**Issue by Mango2020** [nginxinc/docker-nginx-unprivileged#90]
There is 1 high vulnerability issues in nginxinc/nginx-unprivileged@sha256:54b2d0d8ab8891225a824a1e3e1980ee187f17518517a778e7bacb476731a62b which was released on April 21. Would you please help fix it? Thanks.

Details above :
High severity vulnerability found in gzip
Description: An arbitrary file write vulnerability was found in GNU gzip's zgrep utility. When zgrep is applied on the attacker's chosen file name (for example, a crafted file name), this can overwrite an attacker's content to an arbitrary attacker-selected file. This flaw occurs due to insufficient validation when processing filenames with two or more newlines where selected content and the target file names are embedded in crafted multi-line file names. This flaw allows a remote, low privileged attacker to force zgrep to write arbitrary files on the system.
Info: https://www.whitesourcesoftware.com/vulnerability-database/CVE-2022-1271
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/61238245/164651158-9929f879-efda-4e00-9919-fb93e400e941.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/61238245/164651379-ea811ede-db3a-459e-b26f-2d44967fc876.png">

**Comment by Mango2020** [comment]
![Uploading image.png…]()

**Comment by Mango2020** [comment]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/61238245/164674834-16744a5f-36b5-4b51-8885-67f3f05d0d3f.png">

**Comment by alessfg** [comment]
Couple things here:
1) I would have appreciated if you reopened issue #89 like I asked.
2) The images were rebuilt yesterday so it seems as if the security vulnerability has not been fixed in the base Debian bullseye image. The images will be rebuilt again Sunday/Monday night so if the package has been updated by then in the base Debian bullseye image, it will also get fixed in the new weekly image. Given that this is a mirror of the upstream Docker NGINX image, I would rather avoid modifying the Dockerfiles found in this repo I can help it.
